runtime: java17
instance_class: F1

entrypoint: java -jar server-0.0.1-SNAPSHOT.jar

env_variables:
  SPRING_PROFILES_ACTIVE: "production"
  CLOUD_SQL_INSTANCE_CONNECTION_NAME: "grindgauge-project:us-central1:grindgauge-db"
  CLOUD_SQL_DATABASE_NAME: "grindgauge"
  DB_USERNAME: "postgres"
  DB_PASSWORD: "s9d0@kdK2"

automatic_scaling:
  min_instances: 0
  max_instances: 1
  target_cpu_utilization: 0.65

handlers:
- url: /.*
  script: auto
  secure: always
